global:
  env: 
    "ASPNETCORE_ENVIRONMENT": "Development"

library-auth:
  replicaCount: 1

  image:
    repository: matheus06/library-auth
    pullPolicy: IfNotPresent
    tag: "2.0.7"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: library.localdev.me
        paths:
          - path: /(auth/|api/auth/|auth/login|api/users)
            pathType: Prefix

  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "library-auth"
    dapr.io/app-port: "80"
    dapr.io/enable-api-logging: "true"  

  livenessProbe: /health
  readinessProbe: /health

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

library-books:
  replicaCount: 1

  image:
    repository: matheus06/library-books
    pullPolicy: IfNotPresent
    tag: "2.0.7"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: library.localdev.me
        paths:
         - path: /(api/category)
           pathType: Prefix
         - path: /(api/author)
           pathType: Prefix
         - path: /(api/book)
           pathType: Prefix

  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "library-books"
    dapr.io/app-port: "80"
    dapr.io/enable-api-logging: "true"  

  livenessProbe: /health
  readinessProbe: /health

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

library-hub:
  replicaCount: 1

  image:
    repository: matheus06/library-hub
    pullPolicy: IfNotPresent
    tag: "2.0.8"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: library.localdev.me
        paths:
         - path: /(notify)
           pathType: Prefix

  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "library-hub"
    dapr.io/app-port: "80"
    dapr.io/enable-api-logging: "true"  

  livenessProbe: /health
  readinessProbe: /health

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

library-shop:
  replicaCount: 1

  image:
    repository: matheus06/library-shop
    pullPolicy: IfNotPresent
    tag: "2.0.7"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: library.localdev.me
        paths:
         - path: /(api/cart).*
           pathType: Prefix

  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "library-shop"
    dapr.io/app-port: "80"
    dapr.io/enable-api-logging: "true"  

  livenessProbe: /health
  readinessProbe: /health

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

library-ui:
  replicaCount: 1

  image:
    repository: matheus06/library-ui
    pullPolicy: IfNotPresent
    tag: "2.0.7"

  service:
    type: ClusterIP
    port: 80
    targetPort: 4200

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: library.localdev.me
        paths:
         - path: /
           pathType: Prefix

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"