apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pantry-ingress-service
  namespace: pantry
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
    rules:
     - host: pantrymanager-ui.localdev.me
       http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pantry-app-ui-pantry
              port:
                number: 80
     - host: pantrymanager-product-api.localdev.me
       http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pantry-app-product-manager
              port:
                number: 80
     - host: pantrymanager-pantry-api.localdev.me
       http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pantry-app-pantry-manager
              port:
                number: 80
     - host: pantrymanager-recipe-api.localdev.me
       http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pantry-app-recipe-manager
              port:
                number: 80
     - host: pantrymanager-scheduler-api.localdev.me
       http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pantry-app-scheduler
              port:
                number: 80
     - host: pantrymanager-identityserver.localdev.me
       http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pantry-app-identityserver
              port:
                number: 80