# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test Microservice Pantry

on:
  push:
    branches:
      - main
    paths:
      - microservices/microservice.pantrymanager/src/Microservice.PantryManager**
      - microservices/microservice.pantrymanager/test/Microservice.PantryManager.Test**
      - .github/workflows/ms-pantry.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}-api:${{ github.sha }}
          file: ./microservices/microservice.pantrymanager/src/Microservice.PantryManager/Dockerfile

