# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Platform

on:
  push:
    branches:
      - main
    paths:
      - microservices/platform/test/Platform.Test**
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Unit Tests
        uses: ./.github/workflows/unit-test.yml
        with:
          docker_file_path: test

      