name: Reusable workflow example

on:
  workflow_call:
    inputs:
      docker_file_path:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: ${{ inputs.config-path }}